# Generated by Django 3.2.12 on 2022-04-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_basket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
    ]
